<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "{NAME OF EXT}"
 *
 * Auto generated by Extension Builder {DATE}
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Os Iframe',
    'description' => 'Render iframe as Plugin',
    'category' => 'distribution',
    'author' => 'Majd Othman',
    'author_email' => 'majd.os.sy@hotmail.com',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
